### ISSUE TITLE
Add support for Deferred object

### ISSUE THREAD

**Issue by nuragic** [dciccale/kimbo.js#6]
See http://api.jquery.com/category/deferred-object/ :)

**Comment by dciccale** [comment]
finally in july 13, 2015, jquery promises are following the standard http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/
lol

**Comment by dciccale** [comment]
with upcoming ES6 Promise object I think we should move on native adoption.

**Comment by nuragic** [comment]
Yeah, sure I agree! :)
